version: 0.2

phases:
  install:
    runtime-versions:
      java : corretto8
  pre_build:
    commands:
       - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
       - unzip terraform_install.zip -d /usr/bin/
       - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:  
    commands:
       - cd terraform/deploy_container
       - ls -l
       - terraform init -input=false
       - terraform plan
       - terraform apply --auto-approve
artifacts:
  files:
      - target/*.jar
  discard-paths: yes
  base-directory: target
