version: 0.2

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      java : corretto8
  pre_build:
    commands:
       - echo Logging in to Amazon ECR...
       - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k9l5w5o5
  build:  
    commands:
       - mvn package
       - docker build -t test .
       - docker tag test:latest public.ecr.aws/k9l5w5o5/mytest_ecr:latest
       - docker push public.ecr.aws/k9l5w5o5/mytest_ecr:latest
artifacts:
  files:
      - target/*.jar
  discard-paths: yes